# ServiceAccounten er allerede oppretta, kommenterer ut for å unngå å committe client-id unødvendig
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  annotations:
#    azure.workload.identity/client-id:
#  name: blob-demo-sa
#  namespace: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: storage-demo
  name: storage-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: storage-demo
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: blob-demo-sa
      containers:
      - image: mitmproxy/mitmproxy
        name: mitmproxy
        command:
          - "mitmweb"
        args:
          - --web-host
          - 0.0.0.0
        volumeMounts:
          - mountPath: /root/.mitmproxy
            name: shared-certificate
      - image: ghcr.io/christiantryti/storage-test:main@sha256:94f6a904d3e717fd097c5f8a49db6b75a4b2685cfc92a5fca699ada9d93677d0
        imagePullPolicy: Always
        name: storage-test
        ports:
          - containerPort: 8000
            name: http
            protocol: TCP
        command:
          - sh
        args:
          - -c
          - |
            cp /mitmproxy-cert/mitmproxy-ca-cert.pem /etc/ssl/certs/
            /app/app
        env:
          - name: http_proxy
            value: localhost:8080
          - name: https_proxy
            value: localhost:8080
        volumeMounts:
          - mountPath: /mitmproxy-cert
            name: shared-certificate
      volumes:
        - name: shared-certificate
          emptyDir:
            {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storage-demo
  name: storage-demo
  namespace: demo
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: storage-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storage-demo
  namespace: demo
spec:
  ingressClassName: cilium
  rules:
    - host: storage-demo.c.organa.no
      http:
        paths:
          - backend:
              service:
                name: storage-demo
                port:
                  number: 8000
            path: /
            pathType: Exact
---
## Gateway api funka ikke siden selve gatewayen ligger i default, og kan ikke brukes cross-namespace default
#apiVersion: gateway.networking.k8s.io/v1
#kind: HTTPRoute
#metadata:
#  name: storage-demo
#  namespace: demo
#spec:
#  hostnames:
#    - storage-demo.c.organa.no
#  parentRefs:
#    - group: gateway.networking.k8s.io
#      kind: Gateway
#      name: nginx-gateway
#      namespace: default
#  rules:
#    - backendRefs:
#        - kind: Service
#          name: storage-demo
#          port: 8080
#      matches:
#        - path:
#            type: PathPrefix
#            value: /
